// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-e1jsGzQjKAuhtZKUht10t7KruOPQ9BQ',
    appId: '1:1063642821901:web:0ca526c286d10e9b162c44',
    messagingSenderId: '1063642821901',
    projectId: 'outexplore-e2700',
    authDomain: 'outexplore-e2700.firebaseapp.com',
    storageBucket: 'outexplore-e2700.firebasestorage.app',
    measurementId: 'G-6NF6PP9LDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UWspTPvlXX9lXLSdxYVwuGG6b6T_im4',
    appId: '1:788964180825:android:aa0f32ce12816fea68c248',
    messagingSenderId: '788964180825',
    projectId: 'outexplore1',
    storageBucket: 'outexplore1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrrkV5c3R4D8diBopHt-djSqr-kaehxZ8',
    appId: '1:788964180825:ios:a98f6b9203c136b968c248',
    messagingSenderId: '788964180825',
    projectId: 'outexplore1',
    storageBucket: 'outexplore1.firebasestorage.app',
    iosBundleId: 'com.example.sampo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-e1jsGzQjKAuhtZKUht10t7KruOPQ9BQ',
    appId: '1:1063642821901:web:398db62024925095162c44',
    messagingSenderId: '1063642821901',
    projectId: 'outexplore-e2700',
    authDomain: 'outexplore-e2700.firebaseapp.com',
    storageBucket: 'outexplore-e2700.firebasestorage.app',
    measurementId: 'G-08Y49FS5LD',
  );
}